- name: Display Ansible Facts
  hosts: all
  tasks:
    - name: Read ansible facts file
      slurp:
        src: /tmp/ansible_facts.json
      register: facts_file

    - name: Convert facts to JSON
      set_fact:
        ansible_facts: "{{ facts_file.content | b64decode | from_json }}"

    - name: Display Ansible facts
      debug:
        var: ansible_facts
