- name: Gather Ansible Facts
  hosts: all
  tasks:
    - name: Gather facts
      setup:
    - name: Save facts to a file
      copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: /tmp/ansible_facts.json
