---
- hosts: all
  no_log: True
  tasks:
    - name: Capture Ansible facts
      set_fact:
        data:
             my_facts: "{{ ansible_facts }}"
      
    - name: Display captured facts
      debug:
        msg: "{{ my_facts }}"
